name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    # required only if you want to verify Java code
    - name: Install dependencies (Java)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'

    - name: Set up Rust (1.70.0)
      run: |
        rustup set profile minimal
        rustup install 1.70.0
        rustup override set nightly

    # required by cargo-udeps
    - name: Set up Rust (nightly)
      run: |
        rustup set profile minimal
        rustup install nightly
        rustup override set nightly

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
