name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        TZ: 'Asia/Tokyo'
      run: |
        export -p
        export -n GITHUB_ACTION
        export -n GITHUB_ACTIONS
        export -n GITHUB_ACTION_REF
        export -n GITHUB_ACTION_REPOSITORY
        export -p
        oj-verify docs